# Generated by Django 4.2.11 on 2024-04-25 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teryt", "0007_change_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jednostkaadministracyjna",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelOptions(
            name="miejscowosc",
            options={"default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="jednostkaadministracyjna",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="miejscowosc",
            managers=[],
        ),
    ]
