# Generated by Django 2.2.28 on 2024-04-26 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teryt', '0007_change_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jednostkaadministracyjna',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='miejscowosc',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='jednostkaadministracyjna',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='miejscowosc',
            managers=[
            ],
        ),
    ]
